# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1
  - nightly
os:
  - linux
  - osx
  - windows
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: Documentation
      julia: nightly
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = nightly ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
    fi

